# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cls.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tcls.proto\x12\x03\x63ls\"b\n\x03Log\x12\x10\n\x04time\x18\x01 \x02(\x03\x42\x02\x30\x01\x12\"\n\x08\x63ontents\x18\x02 \x03(\x0b\x32\x10.cls.Log.Content\x1a%\n\x07\x43ontent\x12\x0b\n\x03key\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\t\"$\n\x06LogTag\x12\x0b\n\x03key\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\t\"w\n\x08LogGroup\x12\x16\n\x04logs\x18\x01 \x03(\x0b\x32\x08.cls.Log\x12\x13\n\x0b\x63ontextFlow\x18\x02 \x01(\t\x12\x10\n\x08\x66ilename\x18\x03 \x01(\t\x12\x0e\n\x06source\x18\x04 \x01(\t\x12\x1c\n\x07logTags\x18\x05 \x03(\x0b\x32\x0b.cls.LogTag\"3\n\x0cLogGroupList\x12#\n\x0clogGroupList\x18\x01 \x03(\x0b\x32\r.cls.LogGroup')



_LOG = DESCRIPTOR.message_types_by_name['Log']
_LOG_CONTENT = _LOG.nested_types_by_name['Content']
_LOGTAG = DESCRIPTOR.message_types_by_name['LogTag']
_LOGGROUP = DESCRIPTOR.message_types_by_name['LogGroup']
_LOGGROUPLIST = DESCRIPTOR.message_types_by_name['LogGroupList']
Log = _reflection.GeneratedProtocolMessageType('Log', (_message.Message,), {

  'Content' : _reflection.GeneratedProtocolMessageType('Content', (_message.Message,), {
    'DESCRIPTOR' : _LOG_CONTENT,
    '__module__' : 'cls_pb2'
    # @@protoc_insertion_point(class_scope:cls.Log.Content)
    })
  ,
  'DESCRIPTOR' : _LOG,
  '__module__' : 'cls_pb2'
  # @@protoc_insertion_point(class_scope:cls.Log)
  })
_sym_db.RegisterMessage(Log)
_sym_db.RegisterMessage(Log.Content)

LogTag = _reflection.GeneratedProtocolMessageType('LogTag', (_message.Message,), {
  'DESCRIPTOR' : _LOGTAG,
  '__module__' : 'cls_pb2'
  # @@protoc_insertion_point(class_scope:cls.LogTag)
  })
_sym_db.RegisterMessage(LogTag)

LogGroup = _reflection.GeneratedProtocolMessageType('LogGroup', (_message.Message,), {
  'DESCRIPTOR' : _LOGGROUP,
  '__module__' : 'cls_pb2'
  # @@protoc_insertion_point(class_scope:cls.LogGroup)
  })
_sym_db.RegisterMessage(LogGroup)

LogGroupList = _reflection.GeneratedProtocolMessageType('LogGroupList', (_message.Message,), {
  'DESCRIPTOR' : _LOGGROUPLIST,
  '__module__' : 'cls_pb2'
  # @@protoc_insertion_point(class_scope:cls.LogGroupList)
  })
_sym_db.RegisterMessage(LogGroupList)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOG.fields_by_name['time']._options = None
  _LOG.fields_by_name['time']._serialized_options = b'0\001'
  _LOG._serialized_start=18
  _LOG._serialized_end=116
  _LOG_CONTENT._serialized_start=79
  _LOG_CONTENT._serialized_end=116
  _LOGTAG._serialized_start=118
  _LOGTAG._serialized_end=154
  _LOGGROUP._serialized_start=156
  _LOGGROUP._serialized_end=275
  _LOGGROUPLIST._serialized_start=277
  _LOGGROUPLIST._serialized_end=328
# @@protoc_insertion_point(module_scope)
